# TODO: What is really necessary here?
server {
    listen 80;
    # TODO: how to inject it dynamically?
    # server_name ${COOLIFY_URL};
    server_name http://z8sgscgcok4ggcow4k0skw48.49.12.196.173.sslip.io/

    root /var/www/craftcms/web; 
    index index.php index.html index.htm;

    # Main location block
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP handling
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;  # Adjust to the version of PHP you’re using
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors on;
    }

    # Static file handling
    location ~* \.(jpg|jpeg|gif|css|png|js|ico|webp|svg|ttf|woff|woff2)$ {
        expires max;
        log_not_found off;
    }

    # Deny access to hidden files (like .htaccess)
    location ~ /\. {
        deny all;
    }
}
